// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iyccgyqynxwwhctyhdfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5Y2NneXF5bnh3d2hjdHloZGZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDcyODAsImV4cCI6MjA2ODUyMzI4MH0.N85v_K-RCO_Yy8nr2zypIyBqn2DrgkjIuw9YNVHOnWQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});